name: synthetic
channels:
  - conda-forge
dependencies:
  - folium==0.13.0
  - matplotlib==3.7.1
  - numpy==1.24.1
  - pandas==1.5.3
  - pvlib==0.9.4
  - scikit_learn==1.2.1
  - scipy==1.10.1
  - seaborn==0.12.2
  - statsmodels==0.13.5